config/routes.rb
SampleGallery::Application.routes.draw do
  get "bookings/new"

  get "bookings/index"

  get "bookings/edit"

  get "bookings/destroy"

  resources :artlessons

  resources :bookings

  get "artlessons/index"

  get "artlessons/new"

  get "artlessons/edit"

  get "aboutapp/about"

  get "aboutapp/credits"

  get "aboutapp/contact"

  get "home/index"

   root :to => 'home#index'

end

app/models/artlesson.rb
class Artlesson < ActiveRecord::Base
  attr_accessible :description, :no_of_weeks, :places, :price, :start_date, :teacher, :title

  validates :description, :no_of_weeks, :price, :teacher, :title, :places, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :no_of_weeks, :places, numericality: {greater_than_or_equal_to: 1}

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :address, :email, :firstname, :payment_type, :phone_no, :surname

  belongs_to :artlesson

  validates :firstname, :surname, :address, presence: true
  validates :email,
            presence: true,
            :uniqueness => true,
            :length => {:within => 5..50},
            :format => {:with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}
  PAYMENT_TYPES = [ "Visa", "Mastercard", "Maestro" ]
  validates :name, :address, :email, presence: true
  validates :payment_type, inclusion: PAYMENT_TYPES

end

app/controllers/aboutapp_controller.rb
class AboutappController < ApplicationController
  def about
  end

  def credits
  end

  def contact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artlessons_controller.rb
class ArtlessonsController < ApplicationController
  def index
    @artlessons = Artlesson.order("title")
  end

  def new
    @artlesson = Artlesson.new
  end

  def edit
    @artlesson = Artlesson.find(params[:id])
  end

  def create
    @artlesson = Artlesson.new(params[:artlesson])

      respond_to do |format|
        if @artlesson.save
          format.html { redirect_to root_url, notice: 'Lesson Created.' }
        else
          format.html { render action: "new" }
        end
      end
  end


    def show
      @artlesson = Artlesson.find(params[:id])
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(params[:booking])

    respond_to do |format|
      if @booking.save
        format.html { redirect_to root_url, notice: 'Booking successfully made.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def index
    @bookings = Booking.order("created_at")
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.destroy
  end

  def show
    @booking = Booking.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/aboutapp_helper.rb
module AboutappHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artlessons_helper.rb
module ArtlessonsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/aboutapp/about.html.erb
<% content_for :head do %>
    <title>Sample Gallery: About the App</title>
    <%= stylesheet_link_tag 'aboutapp', :media => "all" %>
<% end %>

<% content_for :left_center do %>
      <h2><span class="head2">About the App</span></h2>
      <br>
      <p>This is a Edutainment application that uses the following;</p>
      <br>
      <ul id="tech_list">
        <li>HTML5, particularly canvas</li>
        <li>CSS3</li>
        <li>Sprite3D (JS API for 3D transforms)</li>
        <li>Javascript</li>
        <li>jQuery</li>
        <li>Ruby on Rails</li>
      </ul>
      <br>
      <p>The purpose of the application is to educate children about Pandas and conservation while also providing a fun
        and simple game for them to play.</p>
      <br>
      <h3><span class="head3">Features</span></h3>
      <br>
      <p>Below are two lists, on the left are current site features, on the right are features to come. Both these lists
        will be updated in the coming weeks. Also on the right you will see a twitter feed from my account, this will
        include updates on the application development for Panda Tickle and other projects I am working on at present.</p>
      <br>
      <table>
        <thead>
        <tr>
          <th>Current Features</th>
          <th>Pending Features</th>
        </tr>
        </thead>
        <tfoot>
        <tr></tr>
        </tfoot>
        <tbody>
        <tr>
          <td>CSS 3D Animation on Home Page</td>
          <td>Make game playable on a mobile device</td>
        </tr>
        <tr>
          <td>Combination of CSS 3D and HTML5 canvas for game</td>
          <td>Make site design responsive</td>
        </tr>
        <tr>
          <td>Use of audio tags for game events</td>
          <td>Add more game controls eg mute button</td>
        </tr>
        <tr>
          <td>Post game scores</td>
          <td>Sign in with Facebook and Google+</td>
        </tr>
        <tr>
          <td>CSS3 slide show, in Panda Facts</td>
          <td>Add game levels</td>
        </tr>
        <tr>
          <td>Sign in with your Twitter ID</td>
          <td>Add user feedback</td>
        </tr>
        </tbody>
      </table>
      <%= link_to "Credits", :controller => 'aboutapp', :action => 'credits', class: 'head3' %>
<% end %>

<% content_for :right_center do %>
    <div id="twitfeed">
      <h2>Dev Update</h2>
      <br>
      <ol id="twitter_update_list">
        <li class="tweet"></li>
      </ol>
      <!-- below code taken from Twitter developer help have used my own twitter account to test the code and layout as the gallery haven't yet set up their twitter-->
      <script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
      <script type="text/javascript" src="http://api.twitter.com/1/statuses/user_timeline/kcoughlan78.json?callback=twitterCallback2&amp;count=7"></script>
    </div>
<% end %>

app/views/aboutapp/contact.html.erb
<% content_for :head do %>
    <title>Sample Gallery: Contact Developer</title>
    <%= stylesheet_link_tag 'aboutapp', :media => "all" %>
<% end %>
<% content_for :left_center do %>
<div class = "col_a">
  <div class = "txt">
    <form id="queryForm" onsubmit="return formValidation();" method="post" action="#">
      <p id="error"></p>
      <dl>
        <dt><label for="fullname">Name:</label>
          <input type="text" id="fullname" /></dt>
      </dl>
      <dl>
        <dt><label for="email">E-mail:</label>
          <input type="text" id="email" /></dt>
      </dl>
      <dl>
        <dt>What is the nature of your query?</dt>
        <dt>
          <select title="What can we help you with" id="query">
            <option value="Default" selected="selected">Please select...</option>
            <option value="Membership">Membership</option>
            <option value="Exhibition">Exhibition</option>
            <option value="Courses">Courses</option>
            <option value="Bookshop">Bookshop</option>
            <option value="Facilities">Facilities</option>
            <option value="Other">Other</option>
          </select>
        </dt>
      </dl>
      <p>
        Your message:</p>
      <p><textarea name="comments" id="comments" rows="10" cols="20">How can we help...</textarea></p>
      <dl>
        <dt>Would you like to sign up for our newsletter<input type="checkbox" id="signup" name="subscribe" value="yes" /></dt>
        <dt><input type ="submit" name="submit" value="Submit"/><input id = "reset" type = "reset"/></dt>
      </dl>
    </form>
  </div>
</div>
<% end %>

app/views/aboutapp/credits.html.erb
<% content_for :head do %>
    <title>Sample Gallery: Credits</title>
    <%= stylesheet_link_tag 'aboutapp', :media => "all" %>
<% end %>

<% content_for :left_center do %>
    <h2><span class="head2">Credits</span></h2>
    <br>
    <p>Below are a list of credits for assets used in creating the app.</p>
    <br>
    <p>Games Music: Freedom Dance, UniqueTracks Production Music Library</p>
    <p>Panda Animation Images: Nexon Wizet, The Spriters Resource</p>
    <p>Background Animation Images: Terrariaonline.com</p>
    <br>
    <p>Panda Learning Images:</p>
    <ul id="tech_list">
      <li>wallpup.com</li>
      <li>tumblr.com</li>
      <li>http://www.wallpaperhi.com/</li>
      <li>clker.com</li>
    </ul>
<% end %>

<% content_for :right_center do %>
    <div id="twitfeed">
      <h2>Dev Update</h2>
      <br>
      <ol id="twitter_update_list">
        <li class="tweet"></li>
      </ol>
      <!-- below code taken from Twitter developer help have used my own twitter account to test the code and layout as the gallery haven't yet set up their twitter-->
      <script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
      <script type="text/javascript" src="http://api.twitter.com/1/statuses/user_timeline/kcoughlan78.json?callback=twitterCallback2&amp;count=8"></script>
    </div>
<% end %>

app/views/artlessons/_form.html.erb
<%= form_for(@artlesson) do |f| %>
    <% if @artlesson.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@artlesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

          <ul>
            <% @artlesson.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <table>
      <tr>
        <th></th>
        <th></th>
      </tr>
    <tr><td><%= f.label :title %></td>
<td><%= f.text_field :title %></td></tr>
    <tr><td><%= f.label :description %></td>
      <td><%= f.text_area :description %></td></tr>
    <tr><td><%= f.label :teacher %></td>
      <td><%= f.text_field :teacher %></td></tr>
    <tr><td><%= f.label :start_date %></td>
      <td><%= f.text_field :start_date %></td></tr>
    <tr><td><%= f.label :no_of_weeks %></td>
      <td><%= f.text_field :no_of_weeks %></td></tr>
    <tr><td><%= f.label :places %></td>
      <td><%= f.text_field :places %></td></tr>
    <tr><td><%= f.label :price %></td>
      <td><%= f.text_field :price %></td></tr>
      </table>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/artlessons/edit.html.erb
<% content_for :head do %>
    <title>Sample Gallery: Edit Lesson</title>
    <%= stylesheet_link_tag 'artlessons', :media => "all" %>
<% end %>
<% content_for :center do %>
    <%= render "form" %>
<% end %>

app/views/artlessons/index.html.erb
<% content_for :head do %>
    <title>Sample Gallery: Art Lesson List</title>
    <%= stylesheet_link_tag 'artlessons', :media => "all" %>
<% end %>
<% content_for :center do %>
    <h2><span class='head2'>Our Lessons</span></h2>
    <% @artlessons.each do |lesson| %>
        <article class="<%= cycle('lesson_odd', 'lesson_even') %>">
          <h4><%= link_to lesson.title, lesson %></h4>
          <p><span class="lesson_detail"><%= lesson.created_at.to_s(:short) %></p>
          <p><span class="lesson_detail">by <%= lesson.teacher %></span></p>
          <p><%= truncate(strip_tags(lesson.description), length: 200) %></p>
          <p><%= lesson.no_of_weeks %></p>
          <p><%= lesson.places %></p>
          <p><%= lesson.price %></p>
        </article>
    <% end %>
<% end %>

app/views/artlessons/new.html.erb
<% content_for :head do %>
    <title>Sample Gallery: Create New Lesson</title>
    <%= stylesheet_link_tag 'artlessons', :media => "all" %>
<% end %>
<% content_for :left_center do %>
    <section class="col_a">
    <article id="scroll">
    <%= render "form" %>
    </article>
    </section>
<% end %>

app/views/artlessons/show.html.erb
<% content_for :head do %>
    <title>Sample Gallery: <%= @artlesson.title %></title>
    <%= stylesheet_link_tag 'artlessons', :media => "all" %>
<% end %>
<% content_for :center do %>
    <h2><span class="head2"><%= @artlesson.title %></span></h2>
          <p><span class="lesson_detail"><%= @artlesson.description %></span></p>
          <p><span class="lesson_detail">by <%= @artlesson.teacher %></span></p>
          <p>Starting on the <%= @artlesson.start_date %> for a duration of <%= @artlesson.no_of_weeks %></p>
          <p>Places currently available <%= @artlesson.places %></p>
          <p>Price €<%= @artlesson.price %></p>
    <br>
    <br>
    <%= link_to 'Book a place', new_booking_url %>
    <% end %>

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
    <% if @booking.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this lesson from being saved:</h2>

          <ul>
            <% @booking.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table>
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr><td><%= f.label :firstname %></td>
        <td><%= f.text_field :firstname %></td></tr>
      <tr><td><%= f.label :surname %></td>
        <td><%= f.text_field :surname %></td></tr>
      <tr><td><%= f.label :email %></td>
        <td><%= f.text_field :email %></td></tr>
      <tr><td><%= f.label :address %></td>
        <td><%= f.text_area :address %></td></tr>
      <tr><td><%= f.label :phone_no %></td>
        <td><%= f.text_field :phone_no %></td></tr>
      <tr><td><%= f.label :payment_type %></td>
        <td><%= f.select :payment_type, Booking::PAYMENT_TYPES, prompt: 'Select payment type' %></td></tr>
    </table>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<% content_for :head do %>
    <title>Sample Gallery: Edit a booking</title>
    <%= stylesheet_link_tag 'bookings', :media => "all" %>
<% end %>
<% content_for :center do %>
    <%= render "form" %>
<% end %>

app/views/bookings/index.html.erb
<% content_for :head do %>
    <title>Sample Gallery: Accepted Bookings</title>
    <%= stylesheet_link_tag 'bookings', :media => "all" %>
<% end %>


<h2 class="head2">Bookings</h2>
<br>
<table>
  <tr>
    <th>Firstname</th>
    <th>Surname</th>
    <th>Email</th>
    <th>Address</th>
    <th>Payment</th>
    <th></th>
    <th>Actions</th>
  </tr>

  <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.firstname %></td>
        <td><%= booking.surname %></td>
        <td><%= booking.email %></td>
        <td><%= truncate(strip_tags(booking.address), length: 75) %></td>
        <td><%= booking.payment_type %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <tr>
        <!-- <td>_</td>
         <td>_</td>
         <td>_</td>
         <td>_</td>
         <td>_</td>
         <td>_</td>-->
      </tr>
  <% end %>
</table>

app/views/bookings/new.html.erb
<% content_for :head do %>
    <title>Sample Gallery: Make a booking</title>
    <%= stylesheet_link_tag 'bookings', :media => "all" %>
<% end %>
<% content_for :center do %>
    <%= render "form" %>
<% end %>

app/views/bookings/show.html.erb
<% content_for :head do %>
    <title>Sample Gallery: Accepted Bookings</title>
    <%= stylesheet_link_tag 'bookings', :media => "all" %>
<% end %>
<% content_for :center do %>
    <h2><span class="head2">Your Booking</span></h2>
    <p><%= booking.id %></p>
    <p><%= booking.firstname %> <%= booking.surname %></p>
<% end %>

app/views/home/index.html.erb
<% content_for :head do %>
    <title>Sample Gallery</title>
    <%= stylesheet_link_tag 'home', :media => "all" %>
<% end %>
<% content_for :center do %>
    <div class = "picture">
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "script" %>
  <%= javascript_include_tag "scroll" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id = "box_all"><!--this will contain all other divs and page elements-->
  <section id = "box_top"><!--Broken down into 3 sections left, centre and right will contain logo, menu and social media-->
    <div id = "box_top_left">
      <div class= "pic">
        <br />
        <%= link_to(image_tag("logo.png", alt: "Sample Gallery"), :controller => 'home', :action => 'index')%>
      </div>
    </div>

    <div id="box_top_centre">
      <div id="menu-container">

        <ul id="navigationMenu">

          <li><%=  link_to "Home", root_url, class: 'normalMenu' %></li>
          <li>Exhibitions</li>
          <li><%=  link_to "Lessons", :controller => 'artlessons', :action => 'index', class: 'normalMenu' %></li>
          <li>Bookshop</li>
          <li>About us</li>

        </ul>

      </div>
    </div>

    <div id = "box_top_right">
      <%= link_to(image_tag("twitter_1.png", alt: "Twitter"), "https://twitter.com/kcoughlan78") %>
      <%= link_to(image_tag("fb_1.png", alt: "Facebook"), "https://facebook.com") %>
    </div>
  </section>
  <section id = "box_centre">
    <%= yield :left_center %>
    <%= yield :center %>
    <%= yield :right_center %>
  </section>
  <section id = "box_bottom">
    <div id = "box_bottom_left">
      <div class ="logo">
        <br />
        <%= link_to(image_tag("aclogo.png", alt: "Art Council"), "http://www.artscouncil.ie")%>
      </div>
    </div>
    <div id = "box_bottom_right">
      <div class = "breadcrumbs">
        <!--below are the alternate styles, lightroom and darkroom controlled by the file switcher.js-->
        <p>Choose your style <a href="#" id="Lightroom">Lightroom</a> or
          <a href="#" id="Darkroom">Darkroom</a></p>
      </div>
    </div>
  </section>
</div>
</body>
</html>